import {Sora, Inter} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { StoreProvider } from "@/redux/StoreProvider";
import Footer from "@/components/Footer";



const fontSora = Sora({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	variable: "--font-sora",
});

const fontInter = Inter({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-inter",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${fontSora.variable} ${fontInter.variable}`}
			>
				<StoreProvider>
					<main className=" font-txtFont scroll-smooth overflow-hidden">
						<Navbar />
						{children}
						<Footer />
					</main>
				</StoreProvider>
			</body>
		</html>
	);
}
